Use Univer;
Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
		From AUDITORIUM_TYPE Inner Join AUDITORIUM	
		On AUDITORIUM_TYPE.[AUDITORIUM_TYPE]=AUDITORIUM.AUDITORIUM_TYPE

Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
		From  AUDITORIUM Inner Join AUDITORIUM_TYPE 
		On AUDITORIUM_TYPE.[AUDITORIUM_TYPE]=AUDITORIUM.AUDITORIUM_TYPE
		And AUDITORIUM_TYPE.[AUDITORIUM_TYPENAME] Like '%Компьютер%'

