Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
		From AUDITORIUM, AUDITORIUM_TYPE
		Where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
		From AUDITORIUM, AUDITORIUM_TYPE
		Where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
		And AUDITORIUM_TYPE.AUDITORIUM_TYPENAME Like '%Компьютер%' 