Use Univer;
Select AUDITORIUM_TYPE,AUDITORIUM_CAPACITY
From AUDITORIUM f
Where AUDITORIUM_CAPACITY = (select top(1) AUDITORIUM_CAPACITY from AUDITORIUM p 
where p.AUDITORIUM_TYPE = f.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)